import { StyleSheet } from 'react-native';
import { Colors } from './constants/colors';

export const authStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    padding: 20,
    backgroundColor: Colors.BACKGROUND,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 40,
  },
  title: {
    fontSize: 32,
    fontFamily: 'Poppins_700Bold',
    marginLeft: 10,
    color: Colors.PRIMARY,
  },
  input: {
    height: 50,
    borderColor: Colors.BORDER,
    borderWidth: 1,
    borderRadius: 12,
    marginBottom: 15,
    paddingLeft: 15,
    fontSize: 16,
    fontFamily: 'Poppins_400Regular',
    backgroundColor: Colors.SURFACE,
    color: Colors.TEXT_PRIMARY,
  },
  inputFocused: {
    borderColor: Colors.PRIMARY,
    borderWidth: 2,
    shadowColor: Colors.PRIMARY,
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  bioInput: {
    height: 100,
    textAlignVertical: 'top',
    paddingTop: 15,
  },
  buttonContainer: {
    marginTop: 10,
    borderRadius: 12,
    overflow: 'hidden',
  },
  avatarPicker: {
    alignSelf: 'center',
    marginBottom: 20,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: Colors.SURFACE,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: Colors.BORDER,
  },
  avatar: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  avatarPlaceholder: {
    color: Colors.TEXT_SECONDARY,
    fontFamily: 'Poppins_400Regular',
  },
  label: {
    fontSize: 16,
    fontFamily: 'Poppins_700Bold',
    color: Colors.TEXT_PRIMARY,
    marginBottom: 5,
    paddingLeft: 5,
  },
  errorText: {
    fontFamily: 'Poppins_400Regular',
    color: Colors.DANGER,
    fontSize: 12,
    marginBottom: 5,
    paddingLeft: 10,
  },
  imagePreviewContainer: {
    alignItems: 'center',
    marginVertical: 20,
  },
  imagePreview: {
    width: '100%',
    height: 300,
    borderRadius: 12,
    resizeMode: 'cover',
    borderWidth: 1,
    borderColor: Colors.BORDER,
  },
  imagePlaceholder: {
    width: '100%',
    height: 250,
    borderRadius: 12,
    backgroundColor: Colors.SURFACE,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: Colors.BORDER,
    borderStyle: 'dashed',
  },
});